language: go
before_install:
  - curl -L https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz | sudo tar xJ --strip-components 1 -C /usr/local/bin upx-3.95-amd64_linux/upx
script:
  - make -j$(nproc)
  - go test -test.v ./...
before_deploy:
  - git config --local user.name 'Deskpro'
  - git config --local user.email 'team@deskpro.com'
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'v%Y%m%d%H%M%S')}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: qwe5JL/JBkQUKfnXrxbWGqbXriJ9VaiwlFqEq71ZteIdBMN4FQtxZWq9aHZcNfLxXdjLHviPxupZM1rlXH/hqxltPI4NVQEZY2ayPqS3YCM41VXbh2tgWeIMg+iC6zHFCuYmDJN8b0Z6QUzFR8K3RfI5NDCqP6LJWk9fG6O/Vfrw1rA0cWC3JUa0zBon5HILURnMEVAdC/KcSKqjJL+3tt7F3V64spAKvTOG4NngX25mR5lvd4MJNRk1S9PoH4LBkpgQwCrGqHsncOwsI9llWF7fUxLNHm7U3EJLXGWHYrDGEOTqi6T1STx0X/vdzsAp3CE9fiHlKaFO2UKZLlqBUzHPREVG7N6kdiiBWoUqFDLy77u+WntcynCpDoXC5c1dvko3f/w2x2cNb8hLu5XVNDfVoJ4XwSzlyA2/91Mbs5Wblrksxend0qcEfSRqbpDAY/VazJmdMhjkW7+56PGLabvwuGRnCatHdVZtPJ1Sus7C/2BnXz2TOBnnSDpVLg8424Y/XbiZu5OzLZYtqLK8YjhIpmY5nHkttZP68lXbFIuUgrVasAY0nCld5R1hjjBpb11lYYlT7vkJf53TdkszMpXOjUdJMDVBF5qaXvibgIlWX2i85Dkp8jRr4UlCJLeqgCnMvEY3v9I+YW5a82WaOSPLStkZd1alpOiQ+HKBGg8=
  file_glob: true
  file: build/dputils*
  name: dputils $TRAVIS_TAG
  skip_cleanup: true
  on:
    all_branches: true
