---
name: Build dputils
on:
  push:
    branches:
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: make PACK_EXECUTABLES=0
      - run: go test -test.v ./...
